name: E2E
trigger: [change]
jobs:
  unittest_job:
    name: K8S Unittest
    image: hub.byted.org/codebase/ci_go_1_14:latest
    steps:
      - name: Clone
        uses: actions/checkout
        inputs:
          depth: 1
      - name: Run Unittest
        commands:
          - env
          - export PATH=$PATH:/usr/local/go/bin
          - mkdir -p /go/src/k8s.io
          - cp -rf /home/code /go/src/k8s.io/kubernetes
          - cd /go/src/k8s.io/kubernetes
          - make clean
          - make clean_generated
          - make test
  e2e_job:
    name: K8S E2E
    image: hub.byted.org/data-ci-debian
    steps:
      - name: Clone
        uses: actions/checkout
        inputs:
          depth: 1
      - name: Run E2E Test
        commands:
          - env
          - bash hack/e2e-internal/tce-e2e-run.sh
